const students = [
  {
    number: 1,
    name: "Yash",
    ticket:1,
    rating:5,
    exam:4,
    more:'More Details',
    fullname:'Yash Chaudhary',
    contact:'+91 6281564325',
    email:'yc563782@gmail.com',
    address:' Mathura',
    field:'Web Development'

    },
    {
      number: 2,
      name: "Raj",
      ticket:2,
      rating:3,
      exam:3,
      more:'More Details',
      fullname:'Raj kansana',
      contact:'+91 6281547885',
      email:'kansana1873@gmail.com',
      address:'Madya Pradesh',
      field:'Data Science'

    },
      {
        number: 3,
        name: "Lavish",
        ticket:3,
        rating:5,
        exam:5,
        more:'More Details',
        fullname:'Lavish Gupta',
        contact:'+91 7454005788',
        email:'lg838603@gmail.com',
        address:'Uttar Pradesh',
        field:'DevOps '
  
        },

     {
          number: 4,
          name: "Sachin",
          ticket:4,
          rating:3,
          exam:5,
          more:'More Details',
          fullname:'Sachin Thenua',
          contact:'+91 9918673215',
          email:'sachinthenua312@gmail.com',
          address:'Uttar Pradesh',
          field:'Java Selenium '
    
      },
        {
            number: 5,
            name: "Adarsh",
            ticket:5,
            rating:2,
            exam:3,
            more:'More Details',
            fullname:'Adarsh Rana',
            contact:'+91 9845749871',
            email:'ranaadarsh871@gmail.com',
            address:'Madya Pradesh',
            field:' Cyber Security'
      
         },

    {
        number: 6,
        name: "Sarma",
        ticket:6,
        rating:2,
        exam:4,
        more:'More Details',
        fullname:'Rohith Sarma',
        contact:'+91 627415669',
        email:'Rohithsarma1873@gmail.com',
        address:'Mumbai',
        field:'DevOps'
    },
    {
        number: 7,
        name: "Keshav",
        ticket:7,
        rating:5,
        exam:4,
        more:'More Details',
        fullname:'Keshav Daddhwal',
        contact:'+91 9874522117',
        email:'keshav1273@gmail.com',
        address:'Himachal Pradesh',
        field:'Front-End Engineer'
    },
    {
        number: 8,
        name: "Akshay",
        ticket:8,
        rating:2,
        exam:1,
        more:'More Details',
        fullname:'Akshay Kumar',
        contact:'+91 7287962265',
        email:'akshaykommoju@gmail.com',
        address:'Andhra Pradesh',
        field:'Gem Testing'
    },
    {
        number: 9,
        name: "Vamsi",
        ticket:9,
        rating:0,
        exam:3,
        more:'More Details',
        fullname:'Mandru Vamsi',
        contact:'+91 9866955023',
        email:'mvamsi2001@gmail.com',
        address:'Andhra Pradesh',
        field:'Civil Engineering'
    },
    {
        number: 10,
        name: "Sathvik",
        ticket:10,
        rating:4,
        exam:3,
        more:'More Details',
        fullname:'Sathvik Naidu',
        contact:'+91 6281862555',
        email:'vsathvik1987@gmail.com',
        address:'Bihar',
        field:'Mechanical Engineering'
    },
    {
        number: 11,
        name: "Varun M.V",
        ticket:11,
        rating:3,
        exam:1,
        more:'More Details',
        fullname:'Manda Varun',
        contact:'+91 9584477552',
        email:'varunmv2001@gmail.com',
        address:'Andhra Pradesh',
        field:'PEGA'
    },
    {
        number: 12,
        name: "Joy",
        ticket:12,
        rating:2,
        exam:2,
        more:'More Details',
        fullname:'Joy Dason',
        contact:'+91 9996699658',
        email:'joydason107@gmail.com',
        address:'Kolkata',
        field:'Aero-Space'
    },
    {
        number: 13,
        name: "Jayanth",
        ticket:13,
        rating:0,
        exam:2,
        more:'More Details',
        fullname:'Jayanth Reddy',
        contact:'+91 7032587999',
        email:'vjayanth674@gmail.com',
        address:'Kerala',
        field:'Computer Science'
    },
    {
        number: 14,
        name: "Satya",
        ticket:14,
        rating:2,
        exam:3,
        more:'More Details',
        fullname:'Naga Samudram Satya',
        contact:'+91 9849245228',
        email:'satyanl124@gmail.com',
        address:'Andhra Pradesh',
        field:'Front-End Engineer'
    },
    {
        number: 15,
        name: "Akash",
        ticket:15,
        rating:2,
        exam:2,
        more:'More Details',
        fullname:'Lalith Sai Akash',
        contact:'+91 9866955023',
        email:'klsakash143@gmail.com',
        address:'VishakhaPatnam',
        field:'Software-Developer'
    },
    {
        number: 16,
        name: "Prabhas",
        ticket:16,
        rating:4,
        exam:5,
        more:'More Details',
      fullname:'Uppalapaati Prabhas Varma',
      contact:'+91 9999999998',
      email:'psvarmadarling143@gmail.com',
      address:'Andhra Pradesh',
      field:'Acting'
    },
    {
        number: 17,
        name: "Jasmeet",
        ticket:17,
        rating:2,
        exam:1,
        more:'More Details',
      fullname:'Jasmeet Astwal',
      contact:'+91 6281587562',
      email:'jastwal549@gmail.com',
      address:'Punjab',
      field:'Bussiness Management'
    },
    {
        number: 18,
        name: "Ganesh",
        ticket:18,
        rating:0,
        exam:4,
        more:'More Details',
      fullname:'Alla Ganesh',
      contact:'+91 9587452115',
      email:'aganna143@gmail.com',
      address:'Andhra Pradesh',
      field:'Bussiness Management'
    },
    {
        number: 19,
        name: "Marcus",
        ticket:19,
        rating:0,
        exam:0,
        more:'More Details',
      fullname:'Marcus Lucifer',
      contact:'+91 6000000000',
      email:'mlucifer435@gmail.com',
      address:'Chennai',
      field:'Actor'
    },
    {
        number: 20,
        name: "John",
        ticket:20,
        rating:5,
        exam:0,
        more:'More Details',
      fullname:'John Abraham',
      contact:'+91 6281666666',
      email:'jabraham1853@gmail.com',
      address:'Assam',
      field:'Political Science'
    },
    {
        number: 21,
        name: "Kalyan",
        ticket:21,
        rating:2,
        exam:3,
        more:'More Details',
      fullname:'Kalyan Ram',
      contact:'+91 6281500000',
      email:'nkalyanram0073@gmail.com',
      address:'Andhra Pradesh',
      field:'Acting'
    },
    {
        number: 22,
        name: "Tarak",
        ticket:22,
        rating:4,
        exam:4,
        more:'More Details',
      fullname:'Tarak Reddy',
      contact:'+91 9999547885',
      email:'itarak1000@gmail.com',
      address:'Gujarat',
      field:'Electrical Engineering'
    },
    {
        number: 23,
        name: "Prasanth",
        ticket:23,
        rating:0,
        exam:0,
        more:'More Details',
      fullname:'Siva Prasanth',
      contact:'+91 8888887885',
      email:'kjsprasanth1073@gmail.com',
      address:'Jammu and Kashmir',
      field:'Civil Engineering'
    },
    {
        number: 24,
        name: "Ashok Reddy",
        ticket:24,
        rating:2,
        exam:4,
        more:'More Details',
      fullname:'Ashok Reddy Yerrasaani',
      contact:'+91 6281525247',
      email:'yashokred340@gmail.com',
      address:'Andhra Pradesh',
      field:'Admin Officer'
    },
    {
        number: 25,
        name: "Ajay",
        ticket:25,
        rating:0,
        exam:4,
        more:'More Details',
      fullname:'Ajay Gowd',
      contact:'+91 8881547885',
      email:'gowdajay786@gmail.com',
      address:'Uttar Pradesh',
      field:'Mechanical Engineering'
    },

  ];
  students.forEach((student) => {
    const overallGrade = student.rating + student.exam;
    student.overallGrade = overallGrade;
    student.status = overallGrade >= 4.0 ? "pass" : "fail";
  });
  export default students;